drop table IF EXISTS media ;

create sequence hibernate_sequence start with 1 increment by 1;

create table media (
       id bigint generated by default as identity,
        description varchar(255),
        file blob,
        file_ending varchar(255),
        type integer,
        primary key (id)
    );