package de.klaut.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "Media")
public class Media {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    private String description;

    private Type type;

    private String fileEnding;

    private String fileUrl;

    public Media(MediaDto mediaDto) {
        description = mediaDto.getDescription();
        type = Type.valueOf(mediaDto.getType());
        fileEnding = mediaDto.getFileEnding();
        fileUrl = mediaDto.getFileUrl();
    }
}
