package de.klaut.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

@DynamoDBTable(tableName = "media")
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Media {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String id;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private Type type;

    @DynamoDBAttribute
    private String fileEnding;

    @DynamoDBAttribute
    private String fileUrl;

    public Media(MediaDto mediaDto) {
        id = UUID.randomUUID().toString();
        description = mediaDto.getDescription();
        type = Type.valueOf(mediaDto.getType());
        fileEnding = mediaDto.getFileEnding();
        fileUrl = mediaDto.getFileUrl();
    }

}
