server:
  port: 8080

spring:
  profiles:
    active: "dev"
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---

spring:
  profiles: dev
# Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:file:~/db
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

---

spring:
  profiles: prod

  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: password
 
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
