server:
  port: 8080

spring:
  profiles:
    active: "dev"

---

spring:
  profiles: dev

amazon:
  dynamodb:
    endpoint: http://localhost:8000/
    amazon:
      aws:
        accesskey: AKIAITQDYQG6Q6UWI33Q
        secretkey: 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

---

spring:
  profiles: prod
