server:
  port: 8080

spring:
  profiles:
    active: "dev"

---

spring:
  profiles: dev
# Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:file:~/db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

---

spring:
  profiles: prod

  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
